# Generated by Django 5.2.11 on 2026-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('calor', models.FloatField()),
                ('potencia', models.FloatField()),
                ('potencia_calor', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'bloque_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bloque2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('calor', models.FloatField()),
                ('potencia', models.FloatField()),
                ('potencia_calor', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'bloque_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bloque3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('calor', models.FloatField()),
                ('potencia', models.FloatField()),
                ('potencia_calor', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'bloque_3',
                'managed': False,
            },
        ),
    ]
