# Generated by Django 5.2.11 on 2026-03-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloques', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloque1',
            options={'managed': False, 'verbose_name': 'Bloque 1', 'verbose_name_plural': 'Bloque 1'},
        ),
        migrations.AlterModelOptions(
            name='bloque2',
            options={'managed': False, 'verbose_name': 'Bloque 2', 'verbose_name_plural': 'Bloque 2'},
        ),
        migrations.AlterModelOptions(
            name='bloque3',
            options={'managed': False, 'verbose_name': 'Bloque 3', 'verbose_name_plural': 'Bloque 3'},
        ),
    ]
