name: local
variables:
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0Mjg2MzcyLCJpYXQiOjE3NzQyODYwNzIsImp0aSI6Ijk5NzI0ZjUwMGY2NDQxZjJhNmFhNDc2ZGIxM2M4NjYyIiwidXNlcl9pZCI6IjEifQ.h4e00lCSy6ivx77H6N55uhVpDuPKTtF6CwJp7j9D80g
